nodeshift/openshift-rest-client

- lib/openshift-rest-client.js
- lib/replication-controllers.js
- test/replication-controllers-test.js
> WIP - adding find for replication controllers. 

- lib/replication-controllers.js
- test/replication-controllers-test.js
this calls the DELETE endpoints.
connects to #13
> add a remove method for replication controllers

- lib/build-configs.js
- lib/deployment-config.js
- lib/imagestreams.js
- lib/routes.js
- lib/services.js
- test/build-test.js
- test/deployment-config-test.js
- test/imagestream-test.js
- test/routes-test.js
- test/services-test.js
> make use of the common-request internal module

- lib/deployment-config.js
- lib/routes.js
- lib/services.js
- test/deployment-config-test.js
- test/routes-test.js
- test/services-test.js
> WIP add a remove method for DELETE endpoints

- lib/common-request.js
also depends on https://github.com/bucharest-gold/openshift-config-loader/issues/1
> WIP - adding in a ca prop for request

- index.js
- lib/build-configs.js
- lib/builds.js
- lib/common-request.js
- lib/config-loader.js
- lib/deployment-config.js
- lib/imagestreams.js
- lib/openshift-rest-client.js
- lib/private-map.js
- lib/projects.js
- lib/replication-controllers.js
- lib/routes.js
- lib/services.js
> chore: add license headers. fixes #26

- lib/openshift-rest-client.js
- lib/secrets.js
- test/secrets-test.js
> feat: add api for connecting to the Secrets endpoint

- lib/build-configs.js
- lib/imagestreams.js
- test/build-config-test.js
- test/imagestream-test.js
connects to #37 
WIP while i get all the endpoints added
> WIP - delete endpoints

- lib/common-request.js
@lholmquist sorry - my last PR was broken. This one should do the trick. :)
> fix: use body.message for error string

- lib/common-request.js
> bug(common-request): fixing type error with error message.  fixes #48

- .travis.yml
- README.md
- lib/config-loader.js
- lib/openshift-rest-client.js
- package-lock.json
- package.json
- test/build-config-test.js
- test/build-test.js
- test/cluster-role-binding-test.js
- test/config-loader-test.js
- test/configmaps-test.js
- test/deployment-config-test.js
- test/group-test.js
- test/imagestream-test.js
- test/openshift-client-test.js
- test/pods-test.js
- test/project-request-test.js
- test/projects-test.js
- test/replication-controllers-test.js
- test/role-binding-test.js
- test/routes-test.js
- test/secrets-test.js
- test/services-test.js
The change was pretty straight forward,  just had to update all the tests
connects to #54
> WIP - include config loader

- lib/build-configs.js
- test/build-config-test.js
Also added missing test coverage for instantiateBinary...
> Adding instantiate method to buildconfigs

- lib/events.js
- lib/openshift-rest-client.js
- lib/persistent-volume-claims.js
- test/events-test.js
- test/openshift-client-test.js
- test/persistent-volume-claims-test.js
cleaned up the history from #63
> PVC & Events methods

- lib/ingress.js
- lib/openshift-rest-client.js
- test/ingress-test.js
This uses the extensions/v1beta1 Ingress API.  fixes #73
> feat(ingress): Expose the Ingress api.

- test/common-request-test.js
> WIP - tests for common-request module

- package.json
> chore: remove the call to nsp in the npm prepare script.

- package-lock.json
- package.json
> Greenkeeper/eslint 5.14.1

- README.md
- lib/basic-auth-request.js
- lib/openshift-rest-client.js
- test/basic-auth-request-test.js
- test/openshift-client-test.js
> feat: use a username/password combo to login

- lib/openshift-rest-client.js
> chore: remove unneeded TODO

- index.js
- lib/openshift-rest-client.js
- package-lock.json
- package.json
Related to https://github.com/nodeshift/openshift-rest-client/issues/140
> src: updates kubernetes-client and fix deprecation warnings

- lib/openshift-rest-client.js
- test/openshift-client-test.js
- test/test-config.json
This will add the kubeconfig object to the returned client
fixes #184
> WIP - feat: return the kubeconfig on the client

- lib/openshift-rest-client.js
> docs: Fix the jsdoc in openshift-rest-client.js

- README.md
Documented https://github.com/nodeshift/openshift-rest-client/issues/192 Query Parameters use case
> Updated README with Query Parameters use case

- package-lock.json
- package.json
there is an issue when using kube-client 8.3.7
> fix: pin the kubernetese-client version

- docs/assets/split.js
- package-lock.json
- package.json
- test/authorization-server-request-test.js
- test/basic-auth-request-test.js
- test/binary-build-test.js
- test/openshift-client-test.js
Hey @helio-frota ,
I have fixed all the lint issues in all the 'js' files and removed the es-lint comments too.
In my local all the test cases are passing
Kindly take a look into it.
> Fixing issue: Fix lint issues in the code and remove the eslint comments #308

- lib/basic-auth-request.js
- test/basic-auth-request-test.js
> fix: This fixes the url that is passed into the undici client.

- .github/workflows/nodejs-ci-action.yml
- package.json
> chore: add support for node 22
